server:
  port: 8080
  contextPath: /
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerdb?autoReconnect=true&useSSL=false
    username: root
    password: Powerfulheart7!
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false